name: Test secret



jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo ${{ secrets.TEST }} | base64 >> test.txt
      - name: "22"
        run: cat test.txt
